### ISSUE TITLE
does not install cleanly on plone 4.2rc2

### ISSUE THREAD

**Issue by yurj** [plone/plone.app.workflowmanager#18]
Hi!

 to install p.a.workflowmanager on plone 4.2rc2, I had to add

 plone.app.jquery = 1.7.2

 on buildout.cfg. Otherwise, buildout complained about version 1.4.4 don't fullfill a >= 1.7 constraint.

**Comment by tkimnguyen** [comment]
Sorry @yurj, am closing this since we never got around to it and I suspect this is no longer relevant to version 2.0
