### ISSUE TITLE
Make the diagram more readable

### ISSUE THREAD

**Issue by afrepues** [plone/plone.app.workflowmanager#21]
Shortcoming in the current diagram:

* The initial state is not clear enough, with few states it is fine, but as states are added it gets more difficult to tell
* Using both the title and the ID of the states doesn't enhance the readability while increasing the amount of information to parse
* Important information like the guards is left out
* Restyling it not possible without code modifications

Possible solutions:

* Make the generation of the `DOT` file customizable, by using a template and/or parametrizing its generation (i.e.: `plone.registry`)
* Don't generate an image, but HTML/CSS/JS

Some references:

* Example of cleaner workflow image: http://packtlib.packtpub.com/library/9781904811022/sectiond0e22515#ext-gen1249
* HTML base diagrams: http://boundary.com/blog/2012/07/03/building-node-diagrams-in-html5/

**Comment by tkimnguyen** [comment]
Hi Servilio - have a look at https://github.com/obct537/workflowmanager which is where the UI will change significantly.

**Comment by obct537** [comment]
So, @afrepues, @tkimnguyen is close, but alas, not correct......that link is very much out of date. The most current version is at: https://github.com/plone/plone.app.workflowmanager/tree/overhaul

There's a youtube link demonstrating the new UI....let us know what you think!

**Comment by afrepues** [comment]
@tkimnguyen @obct537 I will take a look at this over the weekend.

**Comment by tkimnguyen** [comment]
I'm going to close this issue since work continues on https://github.com/plone/plone.app.workflowmanager/tree/overhaul and will soon be released as a beta 2.0 (right, @obct537 ? :) )

**Comment by obct537** [comment]
Probably not until after the semester ends, but I plan to make a big push on it this summer :p

**Comment by tkimnguyen** [comment]
OK - I'll be on you like stink at the Mars Cheese Castle :)

**Comment by obct537** [comment]
^ I'm really hoping that there isn't a context in which that makes sense.

**Comment by tkimnguyen** [comment]
@afrepues how does the beta workflow manager look to you?
