### ISSUE TITLE
workflowmanager doesn't pull jquerytools on buildout

### ISSUE THREAD

**Issue by iham** [plone/plone.app.workflowmanager#51]
p.a.wfm depends on p.a.jquerytools (which depends on p.a.jquery), but has nothing specified in setup.py
having to define that in buildout.cfg (or similar) and having to know that is avoidable.

adding p.a.jquerytools to the **install_requires** in setup.py is easy to do.

**Comment by icemac** [comment]
@iham Thanks for bringing this up. Could you create a pull request to fix this issue?

**Comment by icemac** [comment]
@iham Sorry, I did not see your commit before writing. So I'll close the issue.
