### ISSUE TITLE
Where is the 2.0 branch?

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.workflowmanager#63]
On pypi there is a 1.1.0 and a 2.0b1 release, also a https://pypi.org/project/plone.app.workflowmanager-overhaul.
A PR https://github.com/plone/plone.app.workflowmanager/commit/99e629ffc126cb45d3fb4745aee2591c5d13fc61 "Check in plone.app.workflowmanager 2.0b1 (downloaded from pypi)" with 1.2a2 in the changelog and 2.0b1 in setup.py

Can someone clarify? @hvelarde @tisto @tkimnguyen

**Comment by tkimnguyen** [comment]
https://pypi.org/project/plone.app.workflowmanager-overhaul/ was something Sam created to be the 2.0 line of WFM, with a diagram centric UI. Timo, Sam, and I discussed how we would fix some of the confusion in the master branch. Timo subsequently fixed things in the code. https://pypi.org/project/plone.app.workflowmanager-overhaul/ is now out of date and should be removed in favour of WFM 2.0.

**Comment by tkimnguyen** [comment]
OK I see what you mean. I thought we had a 2.0 branch or tag here, but I'm seeing only master and 1.x branches. Maybe @obct537 knows where the 2.0 branch is.

**Comment by tkimnguyen** [comment]
This is the WFM 2.0 on PyPi: https://pypi.org/project/plone.app.workflowmanager/2.0b1/

**Comment by agitator** [comment]
https://github.com/plone/plone.app.workflowmanager/issues/64

**Comment by tkimnguyen** [comment]
Mystery solved! Branch has been restored :) https://github.com/plone/plone.app.workflowmanager/tree/pypi-checkout-2.0b1 thx!
