### ISSUE TITLE
Is uninstall possible

### ISSUE THREAD

**Issue by djowett** [plone/plone.app.workflowmanager#66]
Plone 5.1 flags up a warning that 

    This product cannot be uninstalled!

Is that difficult?  It would be handy now that 2.x is on the scene for those of us who were unaware and installed more than we bargained for ;-)

**Comment by tkimnguyen** [comment]
I think this is just that we did not create an uninstall profile that would in theory clean up any mess left behind. However I don’t think this package changes anything that would break a site after you deactivated it.

**Comment by tkimnguyen** [comment]
I’ve encountered a different problem using this with Plone 5.1 (portal_properties) that I haven’t yet filed an issue for, so beware

**Comment by djowett** [comment]
OK, I did wonder... However downgrading in place did give me subtle Javascript errors because of browser caching.



On 15 February 2019 04:15:40 GMT, "T. Kim Nguyen" <notifications@github.com> wrote:
>I think this is just that we did not create an uninstall profile that
>would in theory clean up any mess left behind. However I don’t think
>this package changes anything that would break a site after you
>deactivated it. >
>>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/plone/plone.app.workflowmanager/issues/66#issuecomment-463900233

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tkimnguyen** [comment]
Downgrading Plone or workflow manager?

**Comment by djowett** [comment]
That was downgrading workflow manager

**Comment by tkimnguyen** [comment]
https://github.com/plone/plone.app.workflowmanager/pull/68

**Comment by tkimnguyen** [comment]
Gaah, test failures...

**Comment by tkimnguyen** [comment]
OK, merged anyway, and new release 2.1.2 at https://pypi.org/project/plone.app.workflowmanager/2.1.2/
